version: "3.8"
services:
  video-stream:
    privileged: true
    build:
      context: .
    command: cargo watch -x 'run  --release --bin video-streaming'
    environment:
      - RUST_LOG=warning
    volumes:
      - /app/target
      - /dev/video0:/dev/video0
      - ./video-streaming:/app/video-streaming
  websocket-server:
    build:
      context: .
    command: cargo watch -x 'run --release --bin websocket-server'
    environment:
      - RUST_LOG=warning
    ports:
      - 8080:8080
    volumes:
      - /app/target
      - ./websocket-server:/app/websocket-server
  web-ui:
    build:
      context: ./web-ui
    ports:
      - 3000:3000
    volumes:
      - ./web-ui/src:/app/src
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
