[package]
name = "websocket-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-nats = "0.10.1"
futures-util = "0.3"
tokio = { version = "1.17.0", features = ["full"] }
warp = "0.3"
